### ISSUE TITLE
[Epic] Products to rebuy

### ISSUE THREAD

**Issue by dominikth13** [dominikth13/SE_Prototype#2]
## User Story
__As a user__ I want to now which products I have to rebuy __so that__ I don't come into the situation that I'm missing products that I need.

## Implementation
We should have a shopping list in the app which is filled in a smart way so that the user automatically finds products in the list which are empty or may be empty. The user should have an option to add products manually e.g. for new products.

### Tasks
- [ ] Create a shopping list
- [ ] Be informed about empty products #1 
- [ ] Be informed about products which mighty become empty soon
- [ ] Have an option to add products manually
